name       : python-tabulate
version    : 0.8.9
release    : 3
source     :
    - https://github.com/astanin/python-tabulate/archive/refs/tags/v0.8.9.tar.gz : 860ffe930003c6895de6e08e73455020c7fccaa034a9e2db344a831dcfa3ed74
homepage   : https://github.com/astanin/python-tabulate
license    : MIT
component  : programming.python
summary    : Pretty-print tabular data in Python, a library and a command-line utility.
description: "Pretty-print tabular data in Python, a library and a command-line utility.   \n"
builddeps  :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
