name       : python-tabulate
version    : 0.8.10
release    : 5
source     :
    - https://github.com/astanin/python-tabulate/archive/refs/tags/v0.8.10.tar.gz : 7a81a625d3cdfdd7c9db25f992410f46e7cbb20ed151126fceeac95586b90284
homepage   : https://github.com/astanin/python-tabulate
license    : MIT
component  : programming.python
summary    : Pretty-print tabular data
description: |
    Pretty-print tabular data in Python, a library and a command-line utility.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
