name       : python-tabulate
version    : 0.8.7
release    : 1
source     :
    - https://github.com/astanin/python-tabulate/archive/v0.8.7.tar.gz : 276c62ff97f9677c6f50a68351f963d09ee1b09b5b62a69775e8c7a81ef34629
homepage   : https://github.com/astanin/python-tabulate
license    : MIT
component  : programming.python
summary    : Pretty-print tabular data in Python, a library and a command-line utility.
description: |
    Pretty-print tabular data in Python, a library and a command-line utility.   
builddeps  :
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
